name = "cyn"
compatibility_date = "2024-05-22"

[build]
command = "npm install && npm run build"
cwd = "."
upload_format = "modules"

[build.upload]
format = "modules"
dir = "dist"

[env.production]
pages_build_output_dir = "./dist"
